### PR TITLE
Recent media pagination

### PR DESCRIPTION
**Pull request by deadkarma**
This is a WIP PR for discussion :)

### CODE REVIEW

**Comment by deadkarma** [comment]
One issue I'm running into is, multiple API calls are not being recorded properly in `ExVCR`, even though the params are different, since the base URL is the same, it looks like it just replays the first call.

**Comment by deadkarma** [comment]
The other `problem` is that the code doesn't feel very "elixir" like, it could probably be refactored/reduced to something simpler :)

**Comment by Zensavona** [comment]
Hey @deadkarma thanks again for this - I'll have a better look when I'm at home and tell you what I think. I've been a bit busy recently so my OS projects have suffered a bit ;)

**Comment by deadkarma** [comment]
@pmarreck if you have some time, could you take a look at let me know what you think as well?

**Comment by Zensavona** [comment]
Hey @deadkarma I had a look. 

If I understand correctly what you're trying to do is this: when the API returns a set of results that is less than the amount requested it's because of pagination, so we request the next set.

What I've experienced using the API (I just tested this again now in case it's changed) is that I can only return 20 results at a time, this number has changed over time so IDK if it's just my account or everyone. I'm not sure how to word this in a really understandable way so here's an example:

```
iex(4)> Elixtagram.user_recent_media(35822824, %{count: 21}) |> Enum.count
20
# no pagination metadata is returned from the server

iex(4)> Elixtagram.user_recent_media(35822824, %{count: 19}) |> Enum.count
19

# pagination metadata is returned, but the second "page" only has one result
```

I tried this in my browser by getting the id of the 19th item in the list and setting that as the `max_id`, lo and behold, I got a response with one result.

What I'm saying is that unless you want to paginate pages with less than 20 results on each this doesn't make much sense, and from your implementation my understanding is that you were just trying to append the results of each "page" to the list, to get the total number of results requested in the `params`. Since we can only request 20 at a time this also doesn't make a whole lot of sense.

Does this all make sense or did I miss something?

Thanks for taking the time to contribute this and the other PR btw, I just released [0.2.8](https://hexdocs.pm/elixtagram/0.2.8) to hex with your defdelegate deprecation patch.

**Comment by deadkarma** [comment]
Basically, when I call `Elixtagram.user_recent_media("123", %{count: 64})`
I am expecting this to return the 64 most recent media posts.

Right now, this function returns at most, 33 results.
This is because the Instagram API returns a maxmimum of 33 results, with a `pagination` struct that contains both `next_url` and `next_max_id` if there are more.
(if `count` is omitted, it seems 20 results is the default)

**Comment by deadkarma** [comment]
Another option is to create a separate function that returns the `pagination` struct back along with the array of `Elixtagram.Model.Media`s to allow clients to handle pagination themselves

**Comment by deadkarma** [comment]
Check https://github.com/Zensavona/elixtagram/pull/11 which is a more flexible solution

**Pull request closed without merging**
